M48
; DRILL file {KiCad 8.0.1} date 2024-08-25T23:19:21+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-25T23:19:21+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
%
G90
G05
T1
X120.4Y-137.5
X120.6Y-148.1
T2
X129.18Y-84.785
X129.18Y-89.635
T3
X126.15Y-84.485
X126.15Y-89.935
M30
